/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ThumbNailView.java
 *
 * Created on 03.04.2010, 14:08:44
 */

package celsius;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;

/**
 *
 * @author cnsaeman
 */
public class ThumbNailView extends javax.swing.JPanel implements TableModelListener, KeyListener {

    public int spx;
    public int spy;

    ItemTable DT;

    boolean updating;

    public int w;
    public int tx;

    private final ArrayList<ThumbNail> Thumbs;

    /** Creates new form ThumbNailView */
    public ThumbNailView(ItemTable dt) {
        initComponents();
        spx=dt.MF.RSC.guiScale(140);
        spy=dt.MF.RSC.guiScale(160);
        Thumbs=new ArrayList<ThumbNail>();
        DT=dt;
        addKeyListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
            public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
            }
            public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                formAncestorResized(evt);
            }
        });
        setLayout(new java.awt.GridLayout(1, 0, 3, 3));
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        adjustGridLayout();
    }//GEN-LAST:event_formComponentResized

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        adjustGridLayout();
    }//GEN-LAST:event_formComponentShown

    private void formAncestorResized(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_formAncestorResized
        adjustGridLayout();
    }//GEN-LAST:event_formAncestorResized

    public void adjustGridLayout() {
        if (updating) return;
        int i=((JScrollPane)getParent().getParent()).getViewport().getWidth();
        if ((i!=0) && (i!=w)) {
            w=i;
            tx=(int)(w/spx);
            if (tx==0) tx=1;
            setLayout(new java.awt.GridLayout(0, tx, 3, 3));
        }
    }

    public void updateView() {
        updating=true; // #### is beeing called four times when changing categories?
        this.removeAll();
        Thumbs.clear();
        for (Item doc : DT.DTM.Items) {
            if (Thumbs.size()<100) { // #### Temp restriction until threadexecutorpool really working
                ThumbNail TN=new ThumbNail(doc,DT);
                Thumbs.add(TN);
                add(TN);
            }
        }
        updating=false;
        w=0;
        adjustGridLayout();
    }

    public void addDoc(int i) {
        ThumbNail TN=new ThumbNail(DT.getItem(i),DT);
        Thumbs.add(i,TN);
        int x=(int) w/spx;
        int y=(int) ((DT.DTM.Items.size() - 0.1) / x + 1);
        setLayout(new java.awt.GridLayout(y, x, 3, 3));
        add(TN,i);
    }

    @Override
    public void remove(int i) {
        if (Thumbs.size()>i) Thumbs.remove(i);
        if (this.getComponentCount()>i) super.remove(i);
    }

    public void tableChanged(TableModelEvent e) {
        if (updating) return;
        if (!Thread.currentThread().getName().startsWith("AWT-Event")) return;
        if (!DT.tableview) {
            if (e.getType()==TableModelEvent.DELETE) {
                for (int i=e.getLastRow();i>=e.getFirstRow();i--) {
                    remove(i);
                }
                int x=(int) w/spx;
                int y=(int) ((DT.DTM.Items.size() - 0.1) / x + 1);
                setLayout(new java.awt.GridLayout(y, x, 3, 3));
            }
            if (e.getType()==TableModelEvent.INSERT) {
                System.out.println("INSERT NOT CAPUTRED");
            }
            if (e.getType()==TableModelEvent.UPDATE) {
                if (e.getLastRow()==-1) {
                    updateView();
                } else {
                    for (int i=e.getFirstRow();i<e.getLastRow()+1;i++) {
                        Thumbs.get(i).updateDoc(DT.getItem(i));
                    }
                }
            }
        }
    }

    public void modifySelection(int i,boolean extend) {
        boolean mod=false;
        if ((i==0) && (DT.selectedlast!=0)) {
            DT.selectedlast=0; mod=true;
        }
        if ((i==1000) && (DT.selectedlast!=DT.DTM.Items.size()-1)) {
            DT.selectedlast=DT.DTM.Items.size()-1; mod=true;
        }
        if ((i>0) && (i<999) && (DT.selectedlast<DT.DTM.Items.size() - i+1)) {
            DT.selectedlast+=i; mod=true;
        }
        if ((i<0) && (DT.selectedlast>i-1)) {
            DT.selectedlast+=i; mod=true;
        }
        if (mod) {
            if (!extend) DT.selectedfirst = DT.selectedlast;
            if (DT.selectedlast > DT.selectedfirst) {
                DT.jtable.getSelectionModel().setSelectionInterval(DT.selectedfirst, DT.selectedlast);
            } else {
                DT.jtable.getSelectionModel().setSelectionInterval(DT.selectedlast, DT.selectedfirst);
            }
            adjustSelection();
        }
    }

    public void keyTyped(KeyEvent e) {
    }

    public void keyPressed(KeyEvent e) {
    }

    public void keyReleased(KeyEvent e) {
        if (e.getKeyCode() == 36)
            modifySelection(0, e.isShiftDown());
        if (e.getKeyCode() == 37)
            modifySelection(-1,e.isShiftDown());
        if (e.getKeyCode() == 39)
            modifySelection(1,e.isShiftDown());
        if (e.getKeyCode() == 38)
            modifySelection(-tx,e.isShiftDown());
        if (e.getKeyCode() == 40)
            modifySelection(tx,e.isShiftDown());
        if (e.getKeyCode()==35) 
            modifySelection(1000,e.isShiftDown());
    }

    public void adjustSelection() {
        scrollRectToVisible(Thumbs.get(DT.selectedlast).getBounds());
        boolean mode=false;
        int b=DT.selectedfirst;
        int e=DT.selectedlast;
        if (b>e) {
            b=DT.selectedlast;
            e=DT.selectedfirst;
        }
        for (int i=0;i<Thumbs.size();i++) {
            if (i==b) mode=!mode;
            if (mode) Thumbs.get(i).setGrey();
            else Thumbs.get(i).setWhite();
            if (i==e) mode=!mode;
        }
    }

    public void update(Item doc) {
        int i=DT.DTM.IDs.indexOf(doc.id);
        Thumbs.get(i).updateDoc(doc);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
