/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * EditLibraryTemplates.java
 *
 * Created on 20.02.2010, 19:01:06
 */

package celsius.Dialogs;

import celsius.MainFrame;
import celsius.Resources;
import celsius.tools.Parser;
import celsius.tools.toolbox;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author cnsaeman
 */
public class EditMyLocation extends javax.swing.JDialog {

    private final MainFrame MF;
    private final Resources RSC;
    private final DefaultListModel DLM;
    private final ArrayList<String> cities;

    /** Creates new form EditLibraryTemplates */
    public EditMyLocation(MainFrame mf, Resources rsc) {
        super(mf, true);
        MF=mf;
        RSC=rsc;
        initComponents();
        DLM=new DefaultListModel();
        cities=new ArrayList<String>();
        try {
            BufferedReader in = new BufferedReader(new InputStreamReader(MainFrame.class.getResourceAsStream("data/places.dat")));
            while (in.ready()) {
                String tmp=in.readLine();
                int i=tmp.indexOf("|");
                DLM.addElement(tmp.substring(0,i).trim());
                cities.add(tmp.substring(i+1).trim());
            }
            in.close();
        } catch (Exception ex) {
            System.out.println("FNF");
        }
        jLCities.setModel(DLM);
        jLCities.setSelectedIndex(-1);
        jTFLat.setText(toolbox.latitudeToString(RSC.mylat));
        jTFLong.setText(toolbox.longitudeToString(RSC.mylon));
        toolbox.centerDialog(this,mf);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLCities = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFLat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTFLong = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jBtnApply = new javax.swing.JButton();
        jBtnDone = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jLCities.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jLCities.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jLCitiesValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jLCities);

        jLabel2.setText("Latitude:");

        jLabel5.setText("Predefined Cities:");

        jLabel6.setText("Longitude:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, RSC.guiScale(236), javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6))
                        .addContainerGap(115, Short.MAX_VALUE))
                    .addComponent(jTFLat, javax.swing.GroupLayout.DEFAULT_SIZE, RSC.guiScale(192), Short.MAX_VALUE)
                    .addComponent(jTFLong, javax.swing.GroupLayout.DEFAULT_SIZE, RSC.guiScale(192), Short.MAX_VALUE)))
            .addComponent(jLabel5)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFLat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFLong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, RSC.guiScale(210), Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(RSC.guiScale(681), RSC.guiScale(35)));

        jBtnApply.setText("Apply");
        jBtnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnApplyActionPerformed(evt);
            }
        });

        jBtnDone.setText("Done");
        jBtnDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnDoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(290, Short.MAX_VALUE)
                .addComponent(jBtnApply)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnDone))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jBtnDone)
                .addComponent(jBtnApply))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnApplyActionPerformed
        try {
            RSC.mylat=toolbox.StringToLatitude(jTFLat.getText());
            RSC.mylon=toolbox.StringToLongitude(jTFLong.getText());
            MF.JM.updateDTs();
        } catch (Exception e) {
            toolbox.Warning(this,"Number format not recognized", "Warning:");
        }
    }//GEN-LAST:event_jBtnApplyActionPerformed

    private void jBtnDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnDoneActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_jBtnDoneActionPerformed

    private void jLCitiesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jLCitiesValueChanged
        String tmp=cities.get(jLCities.getSelectedIndex());
        jTFLat.setText(Parser.CutTill(tmp,"::"));
        jTFLong.setText(Parser.CutFrom(tmp,"::"));
    }//GEN-LAST:event_jLCitiesValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnApply;
    private javax.swing.JButton jBtnDone;
    private javax.swing.JList jLCities;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFLat;
    private javax.swing.JTextField jTFLong;
    // End of variables declaration//GEN-END:variables

}
